products/urls.py
from django.urls import path
from products.views import (
    CustomerInfoUpdateView,
    MembershipDetailView,
    MembershipListView,
)

app_name = "products"
urlpatterns = [
    path("membresias/", MembershipListView.as_view(), name="membership-list"),
    path(
        "membresias/<slug:slug>",
        MembershipDetailView.as_view(),
        name="membership-detail",
    ),
    path(
        "membresias/<slug:slug>/usuario-info/",
        CustomerInfoUpdateView.as_view(),
        name="customer-info",
    ),
]

products/templates/products/includes/membership.html
{% load core_tags %}

<div class="card shadow-lg rounded">
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <h1 class="card-title">{{ membership.name }}</h1>
                <h6 class="card-subtitle mb-2 text-muted">{{ membership.get_display_recurring_price }}</h6>
                <div class="card-text membership-description">
                    <p>{{ membership.short_description|safe }}</p>
                </div>
            </div>
            <div class="col-md-12 text-end">
                <p class="card-text">Pago por ingreso: {{ membership.get_display_entry_cost }}</p>
                <hr>
                <h6 class="card-subtitle mb-2">Total: {{subtotal|cents_to_dollars|dollar_format}}</h6>
            </div>
        </div>
    </div>
</div>

products/templates/products/includes/membership_list.html
{% load core_tags %}

<div class="container px-5 my-5">
    <div class="text-center mb-5">
        <h2 class="fw-bolder text-danger">Membresías</h2>
        <p class="lead mb-0">HAZTE SOCIO HOY DESDE $24.95 AL MES, REPRESENTACION LEGAL ESPECIALIZADA EN LA LEY 168</p>
    </div>
    <div class="row gx-5 justify-content-center">
        
        {% for membership in memberships %}
            <div class="col-lg-6 col-xl-4">
                <div class="card mb-5 mb-xl-0">
                    <div class="card-body p-5">
                        <div class="small text-uppercase fw-bold text-muted">{{membership.name}}</div>
                        <div class="mb-3">
                            <span class="fw-bold fs-xl-25rem fs-xxl-35rem">{{membership.get_recurring_price|dollar_format}}</span>
                            <span class="text-muted">/ {{membership.recurring_payment}}</span>
                        </div>
                        <div class="membership-description mb-3">{{membership.short_description|safe}}</div>
                        <div class="d-grid"><a class="btn btn-outline-danger" href="{% url 'products:membership-detail' membership.slug %}">Ver más</a></div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>