products/urls.py
from django.urls import path
from products.views import (
    CustomerInfoUpdateView,
    MembershipDetailView,
    MembershipListView,
)

app_name = "products"
urlpatterns = [
    path("membresias/", MembershipListView.as_view(), name="membership-list"),
    path(
        "membresias/<slug:slug>",
        MembershipDetailView.as_view(),
        name="membership-detail",
    ),
    path(
        "membresias/<slug:slug>/usuario-info/",
        CustomerInfoUpdateView.as_view(),
        name="customer-info",
    ),
]

products/templates/products/customer_info_form.html
{% extends 'site/base.html' %}

{% block head %}
    <title>{{membership.name}} - Site</title>
{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="text-center">
        {% block title %}
        <h1>Configuremos su cuenta</h1>
        <p>Estás muy cerca de unirte a nuestro plan y obtener los beneficios.</p>
        {% endblock title %}
    </div>
    <div class="row justify-content-center">
        <div class="col-lg-6">
            {% block form %}
            <form method="post">
                {% csrf_token %}
                <!-- User Information Form -->
                <h2>Información del Usuario</h2>
                <div class="row">
                    <div class="mb-4 col-lg-12">
                        <div class="form-floating">
                            {{form.email}}
                            <label for="{{ form.email.id_for_label }}">{{form.email.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.email.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.phone_number}}
                            <label for="{{form.phone_number.id_for_label}}">{{form.phone_number.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.phone_number.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.country}}
                            <label for="{{form.country.id_for_label}}">{{form.country.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.country.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.first_name}}
                            <label for="{{form.first_name.id_for_label}}">{{form.first_name.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.first_name.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.last_name}}
                            <label for="{{form.last_name.id_for_label}}">{{form.last_name.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.last_name.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.address1}}
                            <label for="{{form.address1.id_for_label}}">{{form.address1.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.address1.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.address2}}
                            <label for="{{form.address2.id_for_label}}">{{form.address2.label}}</label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.address2.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.city}}
                            <label for="{{form.city.id_for_label}}">{{form.city.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.city.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.province}}
                            <label for="{{form.province.id_for_label}}">{{form.province.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.province.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.zip}}
                            <label for="{{form.zip.id_for_label}}">{{form.zip.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.zip.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-12">
                        <div class="text-end my-5">
                            {% block extra %}
                                {{form.accept_terms_condition}}
                                <label class="form-check-label" for="{{form.accept_terms_condition.id_for_label}}">
                                    Acepto los <a href="{% url 'terms-conditions' %}">Términos y Condiciones</a> <span class="text-danger">*</span>
                                </label>
                                <div class="text-danger fst-italic">
                                    <ul class="error-list">
                                        {% for error in form.accept_terms_condition.errors %}
                                            <li>{{error}}</li>
                                        {% endfor %}
                                    </ul>
                                </div>                    
                            {% endblock extra %}
                            <button class="btn mt-3" type="submit">Continuar</button>
                        </div>
                    </div>
                </div>
            </form>
            {% endblock form %}
        </div>
        <div class="col-lg-6">
            {% block breakdown %}
            {% include "products/includes/membership.html" %}                
            {% endblock breakdown %}
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/customeruser_update_form.html
{% extends 'site/base.html' %}

{% block head %}
    <title>{{membership.name}} - Site</title>
{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="text-center">
        {% block title %}
        <h1>Configuremos su cuenta</h1>
        <p>Estás muy cerca de unirte a nuestro plan y obtener los beneficios.</p>
        {% endblock title %}
    </div>
    <div class="row justify-content-center">
        <div class="col-lg-6">
            {% block form %}
            <form method="post">
                {% csrf_token %}
                <!-- User Information Form -->
                <h2>Información del Usuario</h2>
                <div class="row">
                    {% if form.non_field_errors %}
                    <div class="my-3 col-lg-12">
                        <div class="text-danger fst-italic">
                            <ul class="error-list">
                                {% for error in form.non_field_errors %}
                                <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    {% endif %}
                    <div class="mb-4 col-lg-12">
                        <div class="form-floating">
                            {{form.email}}
                            <label for="{{ form.email.id_for_label }}">{{form.email.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.email.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.phone_number}}
                            <label for="{{form.phone_number.id_for_label}}">{{form.phone_number.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.phone_number.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.country}}
                            <label for="{{form.country.id_for_label}}">{{form.country.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.country.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.first_name}}
                            <label for="{{form.first_name.id_for_label}}">{{form.first_name.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.first_name.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.last_name}}
                            <label for="{{form.last_name.id_for_label}}">{{form.last_name.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.last_name.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.address1}}
                            <label for="{{form.address1.id_for_label}}">{{form.address1.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.address1.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.address2}}
                            <label for="{{form.address2.id_for_label}}">{{form.address2.label}}</label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.address2.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.city}}
                            <label for="{{form.city.id_for_label}}">{{form.city.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.city.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.province}}
                            <label for="{{form.province.id_for_label}}">{{form.province.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.province.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-sm-6">
                        <div class="form-floating">
                            {{form.zip}}
                            <label for="{{form.zip.id_for_label}}">{{form.zip.label}} <span class="text-danger">*</span></label>
                            <div class="text-danger fst-italic">
                                <ul class="error-list">
                                    {% for error in form.zip.errors %}
                                        <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4 col-12">
                        <div class="text-end my-5">
                            {% block extra %}
                                {{form.accept_terms_condition}}
                                <label class="form-check-label" for="{{form.accept_terms_condition.id_for_label}}">
                                    Acepto los <a href="{% url 'terms-conditions' %}">Términos y Condiciones</a> <span class="text-danger">*</span>
                                </label>
                                <div class="text-danger fst-italic">
                                    <ul class="error-list">
                                        {% for error in form.accept_terms_condition.errors %}
                                            <li>{{error}}</li>
                                        {% endfor %}
                                    </ul>
                                </div>                    
                            {% endblock extra %}
                            <button class="btn mt-3" type="submit">Continuar</button>
                        </div>
                    </div>
                </div>
            </form>
            {% endblock form %}
        </div>
        <div class="col-lg-6">
            {% block breakdown %}
            {% include "products/includes/membership.html" %}                
            {% endblock breakdown %}
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/membership_detail.html
{% extends 'site/base.html' %}

{% block head %}
    <title>{{membership.name}} - Site</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="card shadow-lg my-5">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="card-title">{{ membership.name }}</h1>
                    <h6 class="card-subtitle mb-2 text-muted">{{ membership.get_display_recurring_price }}</h6>
                    <div class="card-text membership-description">
                        {% if membership.long_description %}
                            <p>{{ membership.long_description|safe }}</p>
                        {% else %}
                            <p>{{ membership.short_description|safe }}</p>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-12 text-end">
                    <p class="card-text"><span class="text-muted">Pago por ingreso:</span> {{ membership.get_display_entry_cost }}</p>
                </div>
            </div>
        </div>
    </div>

    <div class="text-end my-5">
        <a class="btn btn-danger mt-3" href="{% url 'products:customer-info' membership.slug %}">Subscribirse</a>
    </div>
</div>
{% endblock %}

products/templates/products/membership_list.html
{% extends 'site/base.html' %}

{% block head %}
    <title>Membresías - Site</title>
{% endblock %}

{% block content %}
{% include "products/includes/membership_list.html" %}
{% endblock %}